### ISSUE TITLE
Expiration time

### ISSUE THREAD

**Issue by matrixik** [NickPresta/chameleon#10]
Would be nice to have expiration time for cache.

**Comment by nickpresta** [comment]
Hey @matrixik, thanks for the suggestion.

I'm trying to understand where an expiration would be used. Would this be something you would expect to have for the responses written to disk, or only responses preseeded (or otherwise stored in memory only)?

**Comment by matrixik** [comment]
I'm thinking here about responses written to disk.
I think that it would be useful for web scraping tests, then I would set expiration time for 24 hours.
And when joined with #9 it would make great testing environment for web scrapers.
